apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubia
spec:
  rules:
    - host: http://35.198.223.189
  http:
    paths:
      - path: /
        backend:
          serviceName: nestjs-service # name of the service inside cluster
          servicePort: 3000