---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-kubernetes-namespace
  name: registry-secret
stringData:
  .dockerconfigjson: |
    {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-kubernetes-secret
stringData:
  REDIS_PASSWORD: REDIS_PASSWORD
  MINIO_PASSWORD: MINIO_PASSWORD
  POSTGRES_PASSWORD: root
  REDIS_URL: redis://:REDIS_PASSWORD@redis-service:6379
  MINIO_URL: minio://minio:MINIO_PASSWORD@minio-service:9000
  POSTGRES_URL: postgres://postgres12:root@postgres-service:5432/test
type: Opaque
