# Default values for example-project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Release-wide Values
# replicas: 3
# version: 'plain-text'

# Service Specific Values
namespaces:
  name: nestjs-kubernetes-namespace
volumes:
  pv:
    name: postgresql-pv
  pvc:
    name: postgresql-pv-claim
secrets:
  name: nestjs-kubernetes-secret
  REDIS_PASSWORD: REDIS_PASSWORD
  MINIO_PASSWORD: MINIO_PASSWORD
  POSTGRES_PASSWORD: postgres
  REDIS_URL: redis://:REDIS_PASSWORD@redis-service:6379
  MINIO_URL: minio://minio:MINIO_PASSWORD@minio-service:9000
  POSTGRES_URL: postgres://postgres12:root@postgres-service:5432/test
redis:
  service:
    name: redis-service
  deployment:
    name: redis-deployment
  container:
    name: redis
    image: redis:5-alpine
postgres:
  service:
    name: postgres-service
  deployment:
    name: postgres-deployment
  container:
    name: postgres
    image: postgres:12-alpine