apiVersion: v1
kind: Service
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: nestjs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nestjs-kubernetes-namespace
  name: nestjs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs
  template:
    metadata:
      labels:
        app: nestjs
    spec:
      containers:
        - name: nestjs
          image: quangkhait98/started-devops_main:v3
          env:
            - name: SERVER_PORT
              value: "4000"
            - name: TYPEORM_HOST
              value: postgres-service
            - name: TYPEORM_USERNAME
              value: root
            - name: TYPEORM_PORT
              value: "5432"
            - name: TYPEORM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nestjs-kubernetes-secret
                  key: POSTGRES_PASSWORD
            - name: TYPEORM_DATABASE
              value: test
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: nestjs-kubernetes-secret
