---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaces.name }}
  name: {{ .Values.postgres.service.name }}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespaces.name }}
  name: {{ .Values.postgres.deployment.name }}
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: {{ .Values.postgres.container.name }}
          image: {{ .Values.postgres.container.image }}
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nestjs-kubernetes-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.volumes.pvc.name }}