apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespaces.name }}
  name: {{ .Values.redis.service.name }}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespaces.name }}
  name: {{ .Values.redis.deployment.name }}
spec:
  selector:
    matchLabels:
      app: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: {{ .Values.redis.container.name }}
        image: {{ .Values.redis.container.image }}
        ports:
        - containerPort: 6379
        args: ["--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nestjs-kubernetes-secret
              key: REDIS_PASSWORD