# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: nestjs-kubernetes-namespace
#   name: registry-secret
# stringData:
#   .dockerconfigjson: |
#     {"auths":{"registry.gitlab.com":{"auth":"AUTH_SECRET_KEY"}}}
# type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespaces.name }}
  name:  {{ .Values.secrets.name }}
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD }}
  MINIO_PASSWORD: {{ .Values.secrets.MINIO_PASSWORD }}
  POSTGRES_PASSWORD: {{ .Values.secrets.POSTGRES_PASSWORD }}
  REDIS_URL: {{ .Values.secrets.REDIS_URL }}
  MINIO_URL: {{ .Values.secrets.MINIO_URL }}
  POSTGRES_URL: {{ .Values.secrets.POSTGRES_URL }}
type: Opaque
